### ISSUE TITLE
Says Something Fishy happened when try to register 

### ISSUE THREAD

**Issue by engineeringstudent0012** [ashu12chi/HealthCastle#1]
When Try to signup and get OTP says something fishy happened 

![photo_2020-10-31_16-15-47](https://user-images.githubusercontent.com/52909024/97776915-5cbe0980-1b94-11eb-93b1-5e65099d413b.jpg)

**Comment by ashu12chi** [comment]
Are you filling all fields according to the constraints. One more question, you are using provided apk or building that by yourself.

**Comment by nisiddharth** [comment]
Is the Ganache server running?

If I remember correctly that message was being displayed when connection
error occurs.

**Comment by ashu12chi** [comment]
@engineeringstudent0012 I downloaded apk and checked by myself, there might be some bug I will check that till then use 7800115772 and 123456 as mobile and password for login into the app. I will check it later

**Comment by engineeringstudent0012** [comment]
I downloaded The Apk provided by You. Thanks for the reply
